### PR TITLE
Beta to Live

### PR DESCRIPTION
**Pull request by Sly777**
- Updated Styles (by @BjornMelgaard)
- Updated Store System (by @BjornMelgaard)
- Fixed Logout Bug (by @BjornMelgaard)
- Added new Command: ```lint:watch``` (by @BjornMelgaard)
- Added Auto check for Js files while dev is running (by @BjornMelgaard)
- Updated Commands Doc

### CODE REVIEW

**Comment by Sly777** [comment]
@BjornMelgaard can you check it last? I will merge it after that.

**Comment by BjornMelgaard** [comment]
@Sly777, yep, all right, data was fine name too, but why not, thanks

**Comment by BjornMelgaard** [comment]
Just thought that someone would like to make store module in same directory with container and name it store too

**Comment by Sly777** [comment]
@BjornMelgaard, I think we can create one CLI command for creating component.

for example;
```yarn run create:component```
-> enter component name: xyz

xyz/index.js
xyz/store.js
xyz/style.js

and boom! everything is ready :D

**Comment by BjornMelgaard** [comment]
@Sly777, no) I mean that name data.js for file that connects container to store is better, because someone like file structure where store module in container directory (like AuthForms/store.js)

**Comment by BjornMelgaard** [comment]
@Sly777 , take a look https://github.com/BjornMelgaard/ran/tree/beta , its with old file structure (features.js with index.js that connects to store), I have [wrote why](https://github.com/Sly777/ran/issues/106#issuecomment-321978694) its better

I want to try `storybook-addon-specifications`  and then I want to merge it.  

`storybook-addon-specifications` will combine test and stories and relieve us from writing `import '~/__mocks__/next-router'` and `import 'jest-styled-components'` separately for two points of entry (`yarn run test` and `yarn run storybook`). 

So when you want tests for component, you write them in `index.stories.js` and you get routers mocking and other automatically, and when you want tests for your component service functions, you write them in `index.test.js`

**Comment by Sly777** [comment]
Hmm, I see. If I understood correctly, You want to use ```store.js``` and ```data.js``` files depends on how you use component, right? If yes, All I can say is It's too much information. Really. Nobody can understand that structure and even I cannot describe it correctly. You don't need to atomize files. ```store.js`` is understandable and enough for creating prototype fastly. And honestly, I don't want to add anything that even I don't understand correctly. Most important thing is RAN must be minimal, really easy-learn.

**Comment by BjornMelgaard** [comment]
@Sly777 , look, right now, in ran's master
https://github.com/Sly777/ran/blob/master/components/CreatePost/store.js - someone look at it and say "aha, all store.js files contain means of connecting component to store"
then he looks at https://github.com/Sly777/ran/blob/master/components/AuthFields/store.js and say "why there store module actually? I expected to see something like connect method"

**Pull request merged**
