### PR TITLE
Auth Fixes

### PR DESCRIPTION
**Pull request by Sly777**
- Fixed Auth Token Bug
- Removed localForage Package
- Added Next-Cookies & Js-Cookie Packages
- Updated Auth Architecture

### CODE REVIEW

**Comment by Sly777** [comment]
@BjornMelgaard @astenmies 

this PR will fix #102 #88 

Can you review the code, please?

**Comment by BjornMelgaard** [comment]
Looks awesome)

**Comment by BjornMelgaard** [comment]
Merge it with master and I'll try to resolve conflicts in https://github.com/Sly777/ran/pull/100

**Comment by BjornMelgaard** [comment]
I will to this)

**Comment by Sly777** [comment]
merged. @BjornMelgaard

**Pull request merged**
