### PR TITLE
REALLY BIG CHANGES (refoldering, jest, tests examples, component-relative images, storybook, logo, nomoresemicolons, )

### PR DESCRIPTION
**Pull request by BjornMelgaard**
related issues:
https://github.com/Sly777/ran/issues/93, https://github.com/Sly777/ran/issues/97, https://github.com/Sly777/ran/issues/106

1. Not all components/containers have tests, cause I dont need them (there exists some examples [#1](https://github.com/SamWyld/resetStore-Issue/blob/master/src/Pokemon.test.js), [#2](https://github.com/NewSpring/Holtzman/blob/e64fe37ff22aefb52bf3e49eb0f09b8156ccb06c/imports/components/content/related-content/__tests__/index.js), but personally I think tests with MockedProvider are flaky, so I am going to hardly use e2e tests and storybook with snapshots, dunno, how you making TTD with graphcool?) ([cool backend lib](https://github.com/charlieschwabacher/gestalt))
2. `schema.graphql` again not in lib, @Sly777 you said you foreshadow several schemas, dunno, it looks prettier)) if someone want several schemas - he made it
3. helper_scripts unchanged)

### CODE REVIEW

**Comment by Sly777** [comment]
Hey @BjornMelgaard, Sorry but I cannot accept this because It's huge. Really. Also, It has significant changes that you didn't ask or suggest (that means we even didn't talk). Even I cannot merge it because of the conflicts. Sorry but I need to close this. Please split your changes and then we can talk (and I can also review).

**Comment by BjornMelgaard** [comment]
@Sly777 , ok, what if I move jest and storybook to another branch, and left all other things, can we then discuss it?

**Comment by Sly777** [comment]
@BjornMelgaard, You need to split to...; (I created this list after checking the files fastly)
- Jest
- Storybook
- Eslint changes
- Stylelint
- Logo
- Offline-ready changes
- Theme
- folder structure
- Others (if there is)

**Comment by Sly777** [comment]
for example; 
- https://github.com/Sly777/ran/pull/125/files#diff-5d0c276360a637d1b787a57760665fbeR12
You made good changes on this line (which it can be important in future) but I cannot merge it because of other changes.

**Comment by BjornMelgaard** [comment]
@Sly777, fk, there's a lot work to do, I even would say its impossible, I can split on jest and others, but *others* are tightly coupled. And I even dont know do you like directory structure (I afraid that changes would be futile). 

I glad to see that you like it, I decided to store images in component directory, [cause storybook does not find the pictures correctly from `/static` directory.](https://github.com/storybooks/storybook/issues/1685)

**Pull request closed without merging**
