### PR TITLE
fix: Adding support for env variable access on the client

### PR DESCRIPTION
**Pull request by mrsteele**

### CODE REVIEW

**Comment by Sly777** [comment]
Hey @mrsteele, It's awesome! But I think we should add prefix for shared env data because most of the people will not know ENV's will be shared with the client if they use it. If we use "PUBLIC_" prefix for ENV, It will only be served on the client as well. What do you think? Otherwise It can be big security hole.

**Comment by mrsteele** [comment]
@sly777 you are suggesting we add something to the documentation to recommend they prefix the public envs with ‘PUBLIC_’?

I actually prefer that as the advanced users who are more comfortable and aware would be able to use it how they please.

Please confirm with me and I will be happy to update the documentation.

**Comment by mrsteele** [comment]
If you meant that you wanted to separate the variables from server and client, dotenv-webpack supports alternative .env files so we can use a completely separate env file (“public.env”) if you prefer.

**Comment by Sly777** [comment]
Nope, I mean we need to filter some important env data on the webpack side. Which means I think we can say "if you add a prefix such as "PUBLIC_" or "P_" on your ENV, These ENVs that has prefix will be also on the client side, Otherwise you cannot access to your ENV data on the client". My concern is people can use ENV without check the documentation (or maybe they even started to use RAN), That time all ENVs data will be on the client side which can be a really big security issue. @mrsteele

**Comment by mrsteele** [comment]
I'll look into it. I like approach B (public.env) more and I believe I have a way to get that into the server as well.

**Comment by mrsteele** [comment]
I just added a fix for the sharing of public and private env variables.

A few important notes about this approach:
1. The client can only access variables in `public.env`.
2. The server will pull in `.env` and `public.env`, however `.env` takes precedence so if the variable is already set in `.env` it wont be overwritten from `public.env`.

If you approve of this approach, I will update the documentation to make these note. I also open to suggestions around this, so feel free to let me know your thoughts.

**Comment by Sly777** [comment]
It looks perfect! 👍

**Comment by Sly777** [comment]
I made some small changes @mrsteele . After the checks, I will merge.

**Pull request merged**
