### PR TITLE
.env support added

### PR DESCRIPTION
**Pull request by fyalavuz**

### CODE REVIEW

**Comment by Sly777** [comment]
Hey @fyalavuz, Can you fix conflicts, please? because I merged the latest version of react-apollo so master has newer one than yours.

Also, can you add small documentation about ".env"? You can write something how you use it, how you split it into dev & prod. It can be reaaalllyy good.

**Comment by Sly777** [comment]
Also I read this about next.js and environment variables. Maybe also we should add these changes.

https://medium.com/the-tech-bench/next-js-environment-variables-d2f6ea1a1dca

**Comment by fyalavuz** [comment]
I wanted to write some docs about it but I couldn't decide to where should I put them. Could you suggest a structure for it? then I'll prepare some docs and I'll re-send a new pull request.

You can reject this one. The link that you wrote is very useful thank you.

**Comment by Sly777** [comment]
https://github.com/Sly777/ran/blob/master/docs/Architecture/environment-variables.md

@fyalavuz, I created the doc for env. So you can update it when u are free.

**Pull request closed without merging**
